### ISSUE TITLE
SGP30 is working with OLED

### ISSUE THREAD

**Issue by TurtleFX** [MallocArray/airgradient_esphome#2]
Hi,

Thanks for your work.
Just want to let you know, that I've used your code as a base and SGP30 sensor is working for me (with OLED attached).
I did not change anything except, obviously, uncommenting all lines related to the SGP30. Also, added "address: 0x58" line, but it is default for the SGP30.
I'm using PCB from Airgradient, SGP30 is connected to the breakout pins (5V, GND, SDA, SCL) on this board. My sensor is from [Aliexpress](https://www.aliexpress.com/item/1005003020863909.html).

**Comment by MallocArray** [comment]
Excellent!  Glad it is working and thanks for the update.

If you haven't already, check out the AirGradient forums where there is a lot of discussion with others working with the same hardware
https://forum.airgradient.com/
