### ISSUE TITLE
ESPhome bme680_bsec component doesnt support the Airgradient one (esp32-c3)

### ISSUE THREAD

**Issue by DreiPixel** [MallocArray/airgradient_esphome#28]
Title.

yeah basically trying to use the bme_680 with the esp32-c3 gives a error that it only supports the esp8266. Esphome uses a old version of bsec where the newer esp32 aren't supported yet.
there is a pull request to fix that tho:
https://github.com/esphome/esphome/pull/4585

and here is a example that works:

https://github.com/esphome/feature-requests/issues/1332#issuecomment-1883976632

**Comment by MallocArray** [comment]
Looks like there isn't much to do in this repo until ESPHome has more native support. 

Or are you trying to use the package file `sensor_bme680.yaml` in this repo?  I could possibly make a copy with the bsec_configuration line added so it might work.
