### ISSUE TITLE
MissingPackageManifestError: Could not find one of 'package.json

### ISSUE THREAD

**Issue by tristartravel** [MallocArray/airgradient_esphome#38]
I have some issue while trying to flash Air Gradient one v9  with ESPhome within Home Assistant ,

The error message i get are as follow 

`INFO ESPHome 2024.2.2
INFO Reading configuration /config/esphome/air.yaml...
INFO Updating https://github.com/MallocArray/airgradient_esphome.git@None
INFO Generating C++ source...
INFO Compiling app...
Processing airgradient-one (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
MissingPackageManifestError: Could not find one of 'package.json' manifest files in the package`

is there any suggestion on how to solve on this issue?

Thanks

HA version 2024.2.5
Esphome Version  2024.2.2

**Comment by MallocArray** [comment]
I haven't been able to reproduce it, but I did find this closed issue that looks similar:
https://github.com/esphome/issues/issues/4272
