### ISSUE TITLE
Connection refused when "Upload to AirGradient Dashboard" is enabled

### ISSUE THREAD

**Issue by andyad8865** [MallocArray/airgradient_esphome#47]
Device info:
- airgradient
- by mallocarray
- Firmware: 2024.3.2 (Apr 13 2024, 14:10:11)
- Hardware: 2.0.1

this is related to #33 

Error:
`[15:22:58][W][http_request:087]: HTTP Request failed; URL: http://hw.airgradient.com/sensors/airgradient:<MAC-ADDR>/measures; Error: connection refused; Duration: 0 ms`

I have edited out the MAC address and replaced it with `<MAC-ADDR>`

i have made sure it is added to the dashboard and the MAC address matches on both the URL in the error and the dashboard
<img width="1491" alt="image" src="https://github.com/MallocArray/airgradient_esphome/assets/25516198/18f19ecc-a120-458d-915d-05382db37d02">

other than that everything appears to work ok with the AG-ONE V9

**Comment by MallocArray** [comment]
Are you setting a static IP in the YAML file, or letting it get one from DHCP?  If static, make sure you have a DNS server defined.

I have the same version of ESPHome working with my ONE, so for troubleshooting you may try using the official AirGradient firmware to see if it works.  That will confirm that the registration on the dashboard is correct.  (Double check that what you added to the dashboard is all lower case and matches what is shown on the ONE display when it first boots up)

**Comment by andyad8865** [comment]
I have just installed the stock firmware from the airgradiant firmware and the dashboard shows the data for the AG-One:
<img width="1873" alt="image" src="https://github.com/MallocArray/airgradient_esphome/assets/25516198/380332be-9105-48ab-9478-afc5b5a39d71">

**Comment by andyad8865** [comment]
i'm going to now reinstall esphome, currently it runs in dhcp mode with the dns server set from the dhcp server

**Comment by andyad8865** [comment]
Ah, I think I have found the issue, it appears it did not pick-up the DNS entries from the DHCP Server and had both DNS entries set at `0.0.0.0`, I have now added a static entry into the config and it is now reporting back.

`[18:43:41][D][http_request:099]: HTTP Request completed; URL: http://hw.airgradient.com/sensors/airgradient:<MAC-ADDR>/measures; Code: 200; Duration: 603 ms`

Sorry for the confusion, it appears I was a little blind when setting up the YAML file

**Comment by MallocArray** [comment]
Odd that it didn't grab DNS from DHCP, but glad you were able to nail it down.  This will be a  good reminder that if others get Connection Refused, to check DNS or add a manual entry.
