### ISSUE TITLE
Could we add device_class: aqi for the aqi sensors and device_class: volatile_organic_compounds for voc sensors?

### ISSUE THREAD

**Issue by ncd7** [MallocArray/airgradient_esphome#68]
**For the AQI**
This will help with some compatibility with other sensors from other integrations (right now my workaround is to add a customize: section to my configuration.yaml file).
Also, if possible pls make sure it is lower case aqi and not AQI because some parts of HA care about a perfect string match which is case sensitive. I believe the correct constant is lower case as I've seen that from other integrations.

**For the VOC**
This might potentially be trickier as the VOC uses an Index and the HA doc states that if you use the device_class: volatile_organic_compounds class you should set the units to µg/m³ but I don't know if that truly matters... I find as a whole the HA meta data about sensors kind of messy. Perhaps only do the AQI above and skip the VOC not sure...

**Comment by MallocArray** [comment]
Are you talking about the device_class for the sensor named "PM 2.5 AQI"?  If so, that looks like a reasonable request.
Regarding the capitalization, are you still taking about `device_class: aqi` being in lower case, or the `unit_of_measurement: "AQI"` part, or talking the name in general?  AQI is an acronym so it should be all caps when talking about it in general and with the name
https://www.airnow.gov/aqi/aqi-basics/
But if you are talking about the unit of measure being lower case, I could be talked into that.  I'm not sure if there is a fixed list of values that unit_of_measure should be, or if it is arbitrary.  Can you include some specific examples of it being lower case in other integrations for comparison?

For VOC, those are all coming from the `sgp4x` sensor integration and it actually specifies `device_class: aqi` for both VOC and NOx Indexes.  If that should be changed, it would be best to open a request in the ESPHome Issues section to see if that maintainer would want to change it, but probably would just leave it alone.

**Comment by MallocArray** [comment]
I have `device_class: aqi` added to the AQI sensor and running it through tests now.  Expect to be included in the next release

**Comment by MallocArray** [comment]
Added in the latest 4.0.0 release
