### ISSUE TITLE
Is ONEv9 sensor truly firing the PM laser every 1 second by default and if so, can it be changed to say 20 seconds (to avoid the fan turning off)?

### ISSUE THREAD

**Issue by ncd7** [MallocArray/airgradient_esphome#69]
I looked at the full documentation (thanks btw, great job on it!) and noticed the package to extend the sensor life.

A few questions:

(1) I'm a bit shocked the default is 1s. That's WAY too frequent and will really wear the sensor. Cannot tell if they are doing it to get you to buy more often :P, can you confirm this is truly the default behavior? Or how could I confirm that myself? I'm asking this because I wouldn't want to mess with the special package if it's not truly needed.

(2) I'd want to increase the sensor sample frequency but still keep it LESS than when the fan turns off as I don't want the added risk of bugs getting inside. How sure are we that the fan stays on for 30 seconds, and if true, can I set the sensor to be 20 seconds? I noticed in your package, the interval must be provided as a string in mins (e.g. "2min"), is it possible to use "20sec"?

I wanted to ask these questions before trying to flash these changes and potentially bricking or messing up the sensor.

Thanks and sorry about all the questions.

**Comment by MallocArray** [comment]
It is certainly every second by default. You can check the logs from the ESPHome device to see it making readings every seconds. To keep from adding unnecessary data to the HomeAssistant database, I currently have it set to get a moving average over 30 readings (30 seconds) and report that.

I've already been testing just changing the `update_interval: 30s` so it only reads once every 30 seconds and reports that.  Any longer and the fan will spin down which could impact readings.  I assume the 30 second spin down based on the documentation for the ESPHome integration in the update_interval section
https://esphome.io/components/sensor/pmsx003.html

I don't really know if the laser is turning off an on at those intervals, or if it only logs that change.  I can't even find anything to backup the claim in that link that the lifespan in 8000 hours for the device. I haven't been able to find that in any spec sheet.

**Comment by MallocArray** [comment]
I tried doing 20 seconds, but the ESPHome component throws a message that says it must be 30s or higher if specifying update_interval, so I guess we'll be doing with 30s
