### ISSUE TITLE
PM 2.5 can go negative in v4.0.0

### ISSUE THREAD

**Issue by joshschaeffer** [MallocArray/airgradient_esphome#72]
I am getting negative PM 2.5 readings from an outdoor O-1PST with the new v4.0.0 build. Seems to occur when the raw reading is bouncing between 0-1 with high humidity.

I am using the standard pms5003t package.

See attached HA screenshot.
<img width="254" alt="Screenshot 2024-07-13 144122" src="https://github.com/user-attachments/assets/075fa9e3-cdd5-4066-a56b-0a3a5272f566">

**Comment by joshschaeffer** [comment]
Nice! Thank you for keeping everything up to date. That correction formula seems like a step in the right direction, and is a big help.

**Comment by MallocArray** [comment]
4.0.1 has been uploaded which should address this. I haven't encountered negative numbers myself, so only assuming that the changes are addressing it.
