### ISSUE TITLE
What packages do I remove to keep everything local to home assistant?

### ISSUE THREAD

**Issue by rshxyz** [MallocArray/airgradient_esphome#87]
what packages do I remove to keep everything local to home assistant?
I think this might be the only one?
```
airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml

https://github.com/MallocArray/airgradient_esphome/blob/main/airgradient-one.yaml
```

**Comment by MallocArray** [comment]
Correct, only the `airgradient_api` line.  Once that is removed, it will not have any code to upload information to the AirGradient dashboard.

You can also turn off the switch "Upload to AirGradient Dashboard" on your device if you want to be able to toggle it off an on easily, but if you don't want it at all, removing that line will not load any of the code.
