### ISSUE TITLE
AQI history doesn't show as graph anymore

### ISSUE THREAD

**Issue by johnbaersdfsfo** [MallocArray/airgradient_esphome#95]
It's been a few weeks now, that if I click on "PM 2.5 AQI" I don't see the graph, but the status bar like this:

![image](https://github.com/user-attachments/assets/25796306-1321-46ff-89cb-11b8652958ff)

I don't think this change was on purpose, was it?

**Comment by MallocArray** [comment]
Interesting.  I suspect it is related to removing the Unit of Measure, which according to HomeAssistant logs was the correct thing to do.  But losing the graph is unexpected and undesired

https://github.com/MallocArray/airgradient_esphome/pull/78

**Comment by MallocArray** [comment]
If you are running a recent version of ESPHome and HomeAssistant can you try again? I didn't change anything related to the Unit of Measure, but my graphs are showing as expected

![image](https://github.com/user-attachments/assets/29594a14-3770-42b2-a695-94c370c3d325)

**Comment by johnbaersdfsfo** [comment]
I can confirm: it is fixed for me, too.
